// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "golang-foo": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/paulcastro/mytest2/design
// --out=$(GOPATH)/src/github.com/paulcastro/mytest2
// --version=v1.3.0

package app

// StatusHref returns the resource href.
func StatusHref() string {
	return "/api/status"
}
